const plantFields = [
	{name: 'tree_id', type: 'hiddenField', error: null, condition: null},
	{name: 'common_name', label: 'common name', type: 'input', error: 'Please enter a common name', condition: 'required'},
	{name: 'other_common_names', label: 'other common names', type: 'input', error: null, condition: null},
	{name: 'slug', label: 'slug', type: 'input', error: 'Please enter a slug', condition: 'required'},
	{name: 'genus_id', label: 'genus', type: 'dropdownSelect', error: null, condition: null},
	{name: 'specific_epithet', label: 'specific epithet', type: 'input', error: null, condition: null},
	{name: 'other_species', label: 'other species', type: 'input', error: null, condition: null},
	{name: 'subspecies', label: 'subspecies', type: 'input', error: null, condition: null},
	{name: 'variety', label: 'variety', type: 'input', error: null, condition: null},
	{name: 'cultivar', label: 'cultivar', type: 'input', error: null, condition: null},
	{name: 'trees_category_id', label: 'category', type: 'dropdownSelect', error: 'Please enter a category', condition: 'required'},
	{name: 'zone_id', label: 'zone', type: 'dropdownSelect', error: null, condition: null},
	{name: 'eco_benefits', label: 'eco benefits', type: 'multiSelect', error: null, condition: null},
	{name: 'native_to', label: 'native to', type: 'multiSelect', error: null, condition: null},
	{name: 'natural_habitat', label: 'natural habitat', type: 'multiSelect', error: null, condition: null},
	{name: 'shapes', label: 'shapes', type: 'multiSelect', error: null, condition: null},
	{name: 'light', label: 'light', type: 'multiSelect', error: null, condition: null},
	{name: 'height_min', label: 'height min', type: 'input', error: null, condition: null},
	{name: 'height_max', label: 'height max', type: 'input', error: null, condition: null},
	{name: 'width_min', label: 'width min', type: 'input', error: null, condition: null},
	{name: 'width_max', label: 'width max', type: 'input', error: null, condition: null},
	{name: 'growth_rate', label: 'growth rate', type: 'dropdownSelect', selectItems: [
            {id: "slow", slug: "slow", name: "slow"},
            {id: "medium", slug: "medium", name: "medium"},
            {id: "fast", slug: "fast", name: "fast"},
          ], error: null, condition: null},
    {name: 'lifespan_min', label: 'lifespan min', type: 'input', error: null, condition: null},
    {name: 'lifespan_max', label: 'lifespan max', type: 'input', error: null, condition: null},
    {name: 'soil', label: 'soil', type: 'multiSelect', error: null, condition: null},
    {name: 'common_uses', label: 'common uses', type: 'multiSelect', error: null, condition: null},
    {name: 'transplanting', label: 'transplanting', type: 'multiSelect', error: null, condition: null},
    {name: 'unique_attractions', label: 'unique attractions', type: 'multiSelect', error: null, condition: null},
    {name: 'tolerances', label: 'tolerances', type: 'multiSelect', error: null, condition: null},
    {name: 'reproduction_type_id', label: 'reproduction types', type: 'dropdownSelect', error: null, condition: null},
    {name: 'seeds_packet', label: 'seeds / packet', type: 'input', error: null, condition: null},
    {name: 'seeds_gram', label: 'seeds / gram', type: 'input', error: null, condition: null},
    {name: 'cost_gram', label: 'cost / gram', type: 'input', error: null, condition: null},
    {name: 'dormancy_treatment_id', label: 'dormancy treatment', type: 'dropdownSelect', error: null, condition: null},
    {name: 'seeding_instructions', label: 'seeding instructions', type: 'textarea', error: null, condition: null},
    // {name: 'insects', label: 'insects', type: 'multiSelect', error: null, condition: null},
    // {name: 'diseases', label: 'diseases', type: 'multiSelect', error: null, condition: null},
    {name: 'body', label: 'body', type: 'textarea', error: null, condition: null},
    {name: 'mode_id', label: 'mode', type: 'dropdownSelect', error: 'Please enter a mode', condition: 'required'},
];

export default plantFields;